--UPDATE ARRANQUE
UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 1)
WHERE id_arranque = 11;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 1)
WHERE id_arranque = 12;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 1)
WHERE id_arranque = 13;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 1)
WHERE id_arranque = 14;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 1)
WHERE id_arranque = 15;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 1)
WHERE id_arranque = 16;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 1)
WHERE id_arranque = 17;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 1)
WHERE id_arranque = 18;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 1)
WHERE id_arranque = 19;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 1)
WHERE id_arranque = 20;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 2)
WHERE id_arranque = 2;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 2)
WHERE id_arranque = 4;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 2)
WHERE id_arranque = 6;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 2)
WHERE id_arranque = 8;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 2)
WHERE id_arranque = 10;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 3)
WHERE id_arranque = 1;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 3)
WHERE id_arranque = 3;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 3)
WHERE id_arranque = 5;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 3)
WHERE id_arranque = 7;

UPDATE ARRANQUE
SET EN_CARRERA = (SELECT REF(c) FROM CARRERA c WHERE c.NUM_CARRERA = 3)
WHERE id_arranque = 9;

--UPDATE CABALLO
UPDATE CABALLO
SET EN_CARRERA = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 3))
WHERE REGISTRO = 'REG001';

UPDATE CABALLO
SET EN_CARRERA = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 2))
WHERE REGISTRO = 'REG002';

UPDATE CABALLO
SET EN_CARRERA = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 3))
WHERE REGISTRO = 'REG003';

UPDATE CABALLO
SET EN_CARRERA = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 2))
WHERE REGISTRO = 'REG004';

UPDATE CABALLO
SET EN_CARRERA = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 3))
WHERE REGISTRO = 'REG005';

UPDATE CABALLO
SET EN_CARRERA = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 2))
WHERE REGISTRO = 'REG006';

UPDATE CABALLO
SET EN_CARRERA = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 3))
WHERE REGISTRO = 'REG007';

UPDATE CABALLO
SET EN_CARRERA = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 2))
WHERE REGISTRO = 'REG008';

UPDATE CABALLO
SET EN_CARRERA = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 3))
WHERE REGISTRO = 'REG009';

UPDATE CABALLO
SET EN_CARRERA = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 2))
WHERE REGISTRO = 'REG010';

--UPDATE DUENO
UPDATE DUENO
SET ES_DUENO = ARR_REF_CABALLO(
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG001'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG004'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG006'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG007'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG010'))
WHERE rfc = 'DA1D6F5V149A8';

UPDATE DUENO
SET ES_DUENO = ARR_REF_CABALLO(
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG002'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG005'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG006'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG007'))
WHERE rfc = 'D465ASD1FEW98';

UPDATE DUENO
SET ES_DUENO = ARR_REF_CABALLO(
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG003'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG004'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG005'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG006'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG007'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG008'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG010'))
WHERE rfc = 'D463JF4JF1MJ3';

UPDATE DUENO
SET ES_DUENO = ARR_REF_CABALLO(
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG004'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG006'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG007'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG008'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG009'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG010'))
WHERE rfc = 'DI16UI491SRTY';

--UPDATE ENTRENADOR
UPDATE ENTRENADOR
SET ENTRENA = ARR_REF_CABALLO(
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG001'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG002'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG003'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG004'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG005'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG006'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG007'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG008'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG009'),
	(SELECT REF(C) FROM CABALLO c WHERE c.registro = 'REG010'))
WHERE rfc = 'E1A6D85197A1W';

--UPDATE JOCKEY
UPDATE JOCKEY
SET arranques = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 1),
    (SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 11))
WHERE rfc = 'JAS5FD3216SDF';

UPDATE JOCKEY
SET arranques = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 2),
    (SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 12))
WHERE rfc = 'JV21A9DA98518';

UPDATE JOCKEY
SET arranques = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 3),
    (SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 13))
WHERE rfc = 'JADS1VA968V1A';

UPDATE JOCKEY
SET arranques = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 4),
    (SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 14))
WHERE rfc = 'J16A987V1AW6R';

UPDATE JOCKEY
SET arranques = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 5),
    (SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 15))
WHERE rfc = 'J19AW5E19SWDA';

UPDATE JOCKEY
SET arranques = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 6),
    (SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 16))
WHERE rfc = 'J1TGW6RT945W9';

UPDATE JOCKEY
SET arranques = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 7),
    (SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 17))
WHERE rfc = 'J51E6FRE874FA';

UPDATE JOCKEY
SET arranques = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 8),
    (SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 18))
WHERE rfc = 'J485FA63E587F';

UPDATE JOCKEY
SET arranques = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 9),
    (SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 19))
WHERE rfc = 'J46SD1AFA876E';

UPDATE JOCKEY
SET arranques = ARR_REF_ARRANQUE(
	(SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 10),
    (SELECT REF(a) FROM ARRANQUE a WHERE a.id_arranque = 20))
WHERE rfc = 'J46DS54A1687F';
